### ISSUE TITLE
Implement M3 server

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-server#30]
# Feature description
Using OpenAPI YAML interface definition files, implement an M3 server for the Python-based Application Server
* Provision and manage the life-cycle of Server Certificate resources.
  * Create, Retrieve, Update, Destroy.
* Provision and manage the life-cycle of Content Hosting Configuration resources.
  * Create, Retrieve, Update, Destroy.
  * Purge the associated content cache.

## Cache purge

For the purposes of the reference implementation using Nginx (which only supports purging individual cache objects, all cache objects under a URL prefix, or all cache objects) only the following very limited subset of regular expressions is supported:
- Most regular expression reserved characters not allowed.
  - Only terminal `.*` allowed, '.' or '*' is not allowed anywhere else in the regular expression unless escaped with `\`.
  - Regular expression not allowed to start with `^` (start of string anchor).
  - `\` may be used to escape characters that would normally be interpreted as regular expression operators.
- Regular expression must be a relative path, not an absolute path.
  - Regular expression is evaluated relative to the AF-defined base URL path.

In case the regular expression does not meet the constrained specification above, a suitable error message (e.g. `400 Bad Request`) should be returned at M3 along with a human-readable error message, e.g. "Regular expression not supported by this implementation". (This error will, in future, be propagated by the 5GMS AF to the M1 client.)

# Relevant specifications and corresponding sections
TS 26.512 plus pre-standardisation M3 Open API YAML interface definition files.

# Additional context
This will allow the 5GMSd AS to be managed by a 5GMSd AF (see 5G-MAG/rt-5gms-application-function#7) or by a test client (see #31). As a consequence, the ability to read a Content Hosting Configuration from a local file should be removed from the 5GMSd AS as part of the scope.

It will be possible for multiple Content Hosting Configurations to be simultaneously provisioned in the 5GMSd AS.

**Comment by davidjwbbc** [comment]
Added M3 interface to the application server on my fork (feature-add-m3-interface branch), and am just running through some tests using curl to mock up client requests and view the responses.

Looking good so far.

**Comment by davidjwbbc** [comment]
During testing of 5G-MAG/rt-5gms-application-function#7, it was noticed that the application server currently only handles HTTP/1.1 for its M3 service. Need to look into how to support HTTP/2 on this interface.

**Comment by davidjwbbc** [comment]
From reading up on the uvicorn github issues about HTTP/2 support, it looks like simply switching from using the uvicorn module to the hypercorn module will enable support for HTTP/1.1 and HTTP/2 (and optionally HTTP/3 if the hypercorn[h3] module installation option is used). I'll modify my current solution to change to the hypercorn python module as the ASGI server.

**Comment by davidjwbbc** [comment]
So using hypercorn, the M3 interface now supports HTTP/1.1, HTTP/2 upgrade and HTTP/2 prior knowledge.

**Comment by davidjwbbc** [comment]
I've been looking at cache purging facilities available with different web server/proxy softwares. This is in order to understand what's possible with each one with respect to implementing the cache purging strategy defined in the 5G specifications.

Here is a table of 4 projects and their cache purging capabilities:
| Software | Purge Object | Purge Whole Cache | Purge Cache Subtree | Purge Cache By Regex |
| :--- | :---: | :---: | :---: | :---: |
| [NGINX](https://nginx.org/en/) | :+1: | :+1: | :+1: | :no_entry: |
| [Varnish](https://varnish-cache.org/) | :+1: | :+1:[^1] | :no_entry: | :no_entry: |
| [Apache HTTPd](https://httpd.apache.org/) | :+1:[^2] | :+1:[^2] | :+1:[^2] | :+1:[^2] |
| [Squid](http://www.squid-cache.org/) | :+1: | :+1:[^1] | :no_entry: | :no_entry: |

[^1]: Achieved by stopping the proxy daemon, deleting the cache and restarting the daemon.
[^2]: Using the external `htcacheclean` command to list all cache entries and/or purge individual cached objects.

All pieces of software are able to purge individual items from their cache.

Two of the web proxies can purge the whole cache while running, two require the daemon to be stopped and the cache deleted.

NGINX can purge a subtree of cache items by using a wildcard symbol (`*`) at the end of a cache key prefix, all items with the same prefix will be purged. To do this in apache the `htcacheclean` command can be used to list all cache entries, filter those that start with a given prefix and use the `htcacheclean` command to delete each one individually. There is a note on the [Squid FAQs suggesting they would like to implement purge by wildcard](https://wiki.squid-cache.org/SquidFaq/OperatingSquid#How_can_I_purge_multiple_objects_from_my_cache.3F) but that this is not currently available.

Only Apache HTTPd can be made to purge by regular expression by using the `htcacheclean` command to list all entries, filter the list using the regular expression and then use `htcacheclean` to delete each item which matched the filter.

**Comment by rjb1000** [comment]
Thanks for the detailed research above, @davidjwbbc.

For the purposes of our reference implementation of the **cache purge operation** using Nginx, I suggest that we support a very limited subset of regular expressions. I have amended the issue description to specify a minimal subset corresponding to Nginx capabilities. (Implementations using different web proxies may implement a different subset of regular expressions, of course.)

**Comment by davidjwbbc** [comment]
I've had an issue implementing the cache purge for NGINX.

So the part I missed when researching the table above is the fact that the cache purger in NGINX is only available in the commercial version, the free version doesn't have a cache purging option built in.

A little looking around the internet suggests other people simply grep for the URL they wish to purge in all files in the cache directory and delete any matching files, then signal NGINX to reload its files. It's not a very nice way of doing it and relies on NGINX storing the cache key in plain text in the cache object files. But this is something we could do in Python. If we're going down this route then this also gives us the freedom to perform the operation using full regular expressions.

**Comment by davidjwbbc** [comment]
To implement manually we can look for `[LF]KEY: <cache-key>[CR][LF]` near the start of the cache file (string appears 336 bytes into the file in the NGINX cache objects I've looked at). Reading the first 4KB of the file and looking for the cache key should do it. If we make sure the cache key contains the provisioning session id followed by the request URL path to the file being requested, then we can ensure that only entries for the correct session are removed. This can be done by using the `proxy_cache_key` directive in the nginx configuration.

**Comment by davidjwbbc** [comment]
Implemented the purge operation as detailed above. Tested this using the test `m3_client_cli.py` command in both purge all and purge regex modes of operation. Cache purged successfully.

I will let @devbbc do some testing against the rt-5gms-application-function with M3 interface. If no problems found then I'll tidy up the commits and generate a PR.

**Comment by devbbc** [comment]
Tested the working of the M3 interface by running this Application Server against the  M3 client enabled rt-5gms-application-function. No problems found in this test and they worked as expected.

**Comment by davidjwbbc** [comment]
While looking at TS 26.512 for 5G-MAG/rt-5gms-application-function#15, I noticed that the cache should be purged when a `ContentHostingConfiguration` is deleted on the M1 interface (or the provisioning session is deleted resulting in the `ContentHostingConfiguration`  resource being deleted). Therefore it makes sense to transfer this logic through the M3 interface so that the cache is purged when a `ContentHostingConfiguration` is deleted via M3. I've implemented this in the 5GMS Application Server as part of this M3 interface, so if a `ContentHostingConfiguration` is deleted, then the NGINX cache is purged of all items for that provisioning session.
